### ISSUE TITLE
Is it compatible with Python 3.6?

### ISSUE THREAD

**Issue by mitar** [byu-dml/metalearn#1]
In primitive's annotation I see only Python 3.5. Does this mean it is not compatible with Python 3.6 and we should not install it/use it with our system running on Python 3.6? If it is, maybe list both under `languages`?

**Comment by csydvs** [comment]
Tested this, and it is compatible with python 3.6. Updated JSON in byu-dml/metalearn repository, and copy in primitives_repo with https://gitlab.datadrivendiscovery.org/jpl/primitives_repo/merge_requests/76
