### ISSUE TITLE
Factor out function to test correct number of metafeatures returned

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#104]

**Comment by macetheace96** [comment]
#102

**Comment by macetheace96** [comment]
since we use the same function to get the number of metafeatures here as the `test_compare_metafeature_lists()`, this issue should be addressed when the `test_compare_metafeature_lists()` function is factored out

**Comment by bjschoenfeld** [comment]
handled by ff631dac47faa6aa2f087a6eec1a3b40e44a36bf
