### ISSUE TITLE
Controlled multiprocessing

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#105]
While there is no explicit multiprocessing yet, metalearn uses as many cores as its dependencies want; in particular, sklearn. There are circumstances in which this behavior is not desirable, like in distributed computing frameworks (like Celery). metalearn should default to using only 1 core and thread unless indicated by the user. For this issue, the goal is to enforce single-core processing. Later we can consider multi-core processing and the relevant api.

**Comment by bjschoenfeld** [comment]
I encountered a deadlock situation. It occurred when sklearn did not have enough instances of data in each class for cross validation. Perhaps we should remove all multiprocessing until we can resolve this.

**Comment by macetheace96** [comment]
I was looking on the sklearn page and I found [this](http://scikit-learn.org/stable/faq.html#why-do-i-sometime-get-a-crash-freeze-with-n-jobs-1-under-osx-or-linux) regarding multiprocessing that might address this issue

**Comment by macetheace96** [comment]
Also, the documentation for `cross_validate()` in sklearn as well as a few other features has this param:

> n_jobs : integer, optional
> The number of CPUs to use to do the computation. -1 means ‘all CPUs’.

**Comment by bjschoenfeld** [comment]
That is good. I think we need to set `n_jobs=1`. This means it will take longer to compute, but it will be controlled and on one process.

**Comment by macetheace96** [comment]
From what I gathered about the multiprocessing part on the sklearn page, all we have to do is set one parameter in the multiprocessing package for it to work as well (something about how it forks new processes). Again this will slow things down but will allow us to maintain the multiprocessing feature.

**Comment by macetheace96** [comment]
>If you have custom code that uses multiprocessing directly instead of using it via joblib you can enable the ‘forkserver’ mode globally for your program: Insert the following instructions in your main script:

```python
 import multiprocessing

# other imports, custom code, load data, define model...
if __name__ == '__main__':
    multiprocessing.set_start_method('forkserver')

    # call scikit-learn utils with n_jobs > 1 here
```

**Comment by macetheace96** [comment]
Interestingly, removing all multiprocessing cut the test time almost in half (from about 15 seconds to about 8), possibly due to the small size of our datasets (the multiprocessing only occurred during cross validation). Maybe in the future, if we decide to re-implement this feature, it would be helpful to inform the user that enabling it would only help under certain conditions (like with very large datasets)

**Comment by bjschoenfeld** [comment]
More and more, I am leaning towards only supporting single core/thread processing. It is less work for us. Any user who wants to parallelize can do so easily by asking for different metafeatures on different cores. @joaquinvanschoren, do you have any thoughts on this?

**Comment by bjschoenfeld** [comment]
Timeouts would be much cleaner. The code would be much simpler and stack traces would be easier to read.

**Comment by bjschoenfeld** [comment]
OpenBLAS is the culprit still. Using `os.environ["OPENBLAS_NUM_THREADS"] = "1"` before `import numpy`  solves the problem. However, we cannot control when the user will import numpy. They may import numpy before importing this package. This easy answer is: let the user control numpy behavior and we control our behavior.

However, we still need to control the timeout functionality. #82

**Comment by bjschoenfeld** [comment]
Timeout has been removed. OpenBLAS has to be controlled by user. All other multiprocessing is set to use 1 core. Open new issue if any still exist.
