### ISSUE TITLE
Exclude metafeatures to compute

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#125]
`Metafeatures.compute` supports computing all or a specified subset of metafeatures. When users want to compute all but a few metafeatures, this requires them to pass in a huge list of metafeatures to compute. Perhaps there could be a part of the API which indicates "compute all but _these_ metafeatures".

**Comment by macetheace96** [comment]
what would be the expected behaviour if an excluded metafeature doesn't exist? Just ignore it or raise an exception/warning?
