### ISSUE TITLE
Soft timeout

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#138]
See [this issue](https://github.com/byu-dml/d3m-primitives/issues/18). A soft timeout means that metafeatures are computed until `timeout` has been exceeded. Then no more are computed and the computed metafeatures are returned.

The simplest version is to check the total compute time after each metafeature is computed.

A more intricate one would check at the beginning of each call of `_get_resource`, `_get_function`, and `_get_arguments`, etc.

**Comment by mitar** [comment]
I think you should just compute all metafeatures requested and leave to TA2 to figure out which one to pick to be under a budget.
