### ISSUE TITLE
Inconsistent number of numeric and categorical features metafeatures in small dataset

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#149]
In the current develop branch, updating the known metafeatures causes the tests to fail on the small test dataset. The metafeatures that are inconsistent are the number of numeric and categorical features. One would think that after re-computing the known values, there would not be errors in testing for correctness. There is probably an inconsistency in how the dataset metadata is loaded, causing the column_types to change slightly between runs of computing metafeatures.

**Comment by macetheace96** [comment]
How likely is it that the failing runs are done with `all_dataset_metadata.json` instead of `test_dataset_metadata.json`? The test one has updated column types but the other one doesn't, so they would give different values for some of the small test dataset's column types...
