### ISSUE TITLE
D3M Dataset Errors/Warnings

### ISSUE THREAD

**Issue by poolguy** [byu-dml/metalearn#17]
1. **LL0_1549_autouniv_au6_750:**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1.

2. **LL0_1520_robot_failures_lp5**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1.

3. **LL0_1493_one_hundred_plants_texture**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1.

4. **LL0_1008_analcatdata_reviewer**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

5. **LL0_333_monks_problems_1**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

6. **LL0_337_spectf**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/covariance/shrunk_covariance_.py:193: UserWarning: Only one sample available. You may want to reshape your data array
  warnings.warn("Only one sample available. "

7. **LL0_40509_Australian**

_Warnings:_
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))

_Errors:_
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/multiclass.py", line 97, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))

8. **LL0_1466_cardiotocography**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

9. **LL0_4153_Smartphone_Based_Recognition_of_Human_Activities**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:77: UserWarning: Maximum number of iterations reached
  warnings.warn('Maximum number of iterations reached')

_Errors:_
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/utils/multiclass.py", line 97, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))

10. **LL0_1501_semeion**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))

11. **LL0_475_analcatdata_germangss**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:77: UserWarning: Maximum number of iterations reached
  warnings.warn('Maximum number of iterations reached')
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))
- [x] metalearn/env/lib/python3.6/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
- [x] metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:4291: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/covariance/shrunk_covariance_.py:193: UserWarning: Only one sample available. You may want to reshape your data array
  warnings.warn("Only one sample available. "

12. **LL0_1531_volcanoes_b1**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

13. **LL0_228_breast_cancer_wisconsin_diagnostic**

_Errors_:
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/utils/multiclass.py", line 97, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))

14. **LL0_335_monks_problems_3**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
 
15. **LL0_1040_sylva_prior**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

16. **LL0_238_drivface**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:313: UserWarning: X scores are null at iteration 0
  warnings.warn('X scores are null at iteration %s' % k)
- [x] metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:4291: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)
- [x] metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:3184: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
- [x] metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:3183: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/covariance/shrunk_covariance_.py:193: UserWarning: Only one sample available. You may want to reshape your data array
  warnings.warn("Only one sample available. "

17. **LL0_1508_user_knowledge**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

18. **LL0_40693_xd6**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

19. **LL0_1041_gina_prior2**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

20. **LL0_1515_micro_mass**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

21. **LL0_478_collins**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

22. **LL0_1176_internet_advertisements**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))

23. **LL0_1036_sylva_agnostic**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

24. **LL0_488_colleges_aaup**

_Warnings_:
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))

_Errors:_
- [x] ValueError: cannot reshape array of size 0 into shape (0,newaxis)

25. **LL0_1529_volcanoes_a3**

_Warnings_:
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

26. **LL0_1100_popularkids**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))
- [x] metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:3183: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
- [x] /metalearn/env/lib/python3.6/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
- [x] /metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:4291: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

27. **LL0_39_ecoli**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/covariance/shrunk_covariance_.py:193: UserWarning: Only one sample available. You may want to reshape your data array
  warnings.warn("Only one sample available. "

28. **LL0_953_splice**

_Warnings_:
- [x] /metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

29. **LL0_186_braziltourism**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/covariance/shrunk_covariance_.py:193: UserWarning: Only one sample available. You may want to reshape your data array
  warnings.warn("Only one sample available. "

30. **LL0_32_pendigits**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

31. **LL0_42_soybean**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:313: UserWarning: X scores are null at iteration 0
  warnings.warn('X scores are null at iteration %s' % k)
- [x] metalearn/env/lib/python3.6/site-packages/numpy/lib/function_base.py:3183: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:77: UserWarning: Maximum number of iterations reached
  warnings.warn('Maximum number of iterations reached')

_Errors:_
- [x] ValueError: cannot reshape array of size 0 into shape (0,newaxis)

32. **LL0_1_anneal**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

33. **LL0_1481_kr_vs_k**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

34. **LL0_40706_parity5_plus_5**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

35. **LL0_1459_artificial_characters**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))

36. **LL0_40649_GAMETES_Heterogeneity_20atts_1600_Het_0**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

37. **LL0_1538_volcanoes_d1**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)

38. **LL0_747_servo**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

39. **LL0_1217_click_prediction_small**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/cross_decomposition/pls_.py:329: RuntimeWarning: invalid value encountered in true_divide
  / np.dot(y_scores.T, y_scores))
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
  % (min_groups, self.n_splits)), Warning)

_Errors:_
- [x] MemoryError

40. **LL0_329_hayes_roth**

_Warnings_:
- [x] metalearn/env/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

41. **LL0_679_rmftsa_sleepdata**

_Errors_:
- [x] ValueError("Unknown label type: %s" % repr(ys))

42. ****

_Warnings_:
- [ ] 

43. ****

_Warnings_:
- [ ] 

44. ****

_Warnings_:
- [ ] 

45. ****

_Warnings_:
- [ ] 

46. ****

_Warnings_:
- [ ] 

47. ****

_Warnings_:
- [ ] 

48. ****

_Warnings_:
- [ ] 

49. ****

_Warnings_:
- [ ] 

50. ****

_Warnings_:
- [ ] 

51. ****

_Warnings_:
- [ ]

**Comment by bjschoenfeld** [comment]
Handled these with #18
