### ISSUE TITLE
Match D3M v2019.5.8 Dependencies

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#173]
See the list of dependencies here: https://gitlab.com/datadrivendiscovery/d3m/blob/v2019.5.8/setup.py

**Comment by epeters3** [comment]
I've verified that the package tests still pass and the `compare_with_openml` method still runs with this updated dependency installed.

**Comment by bjschoenfeld** [comment]
@epeters3 Everytime we submit to D3M, we need to match their dependencies, if possible. Can you check all of them and then let me know when that is done?
