### ISSUE TITLE
Updates to README

### ISSUE THREAD

**Issue by epeters3** [byu-dml/metalearn#178]
These updates to the project readme are proposed:

- The **dependencies list in the readme**, in the "Installing" section may not be needed. It adds a little extra work to the project because if the project dependencies change, that section of the readme also needs to be updated. Also, since those dependencies are installed automatically, maybe they don't need to be mentioned in the readme?
- Does the package have a certain way of detecting **a classification vs. a regression task**? Does that need to be mentioned in the usage/getting started section(s)?
- Add an **"advanced usage" or "filtering metafeatures" section** that describes advanced usage of the package and how to use the group by feature.

**Comment by macetheace96** [comment]
Also, including a CONTRIBUTING.md file might be helpful for the future

**Comment by bjschoenfeld** [comment]
> Also, including a CONTRIBUTING.md file might be helpful for the future

Let's make a separate issue for this.

**Comment by macetheace96** [comment]
I'm not sure about the 'filtering metafeatures section', that might be better to add once we have a more solid grouping mechanism.
