### ISSUE TITLE
Public API should be caller safe

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#21]
Currently, when computing metafeatures, we assume the input of a pandas dataframe. If the user does not give a dataframe, our code will fail, but not in a user friendly way. We should validate all parameters to make sure the user is notified appropriately of errors (to the extent possible).

**Comment by PGijsbers** [comment]
I am not sure you want to (explicitly) type-check *all* parameters on type. But for the dataframe parameter I can imagine it can help usability as perhaps something like a numpy array can also be a quite common data representation.

I set out to add that functionality (and add a unit test for it), and saw that there was no use of any unit test framework, so I opted to also refactor the test_metafeatures to use the built-in unittest module of python (see [here](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaises)). It's not completely finished yet (I want to fix some TODO's that were in the unit test file as well), but the work can be seen in the inputcheck branch ([here](https://github.com/byu-dml/metalearn/tree/inputcheck)).

**Comment by PGijsbers** [comment]
Okay, so far I have also added tests to verify input of the metafeatures parameter (verifying that all requested metafeatures have a corresponding function (not that the function will actually run successfully)).

Additionally I made a test that checks metafeatures against previously computed values (by this module).

**Comment by bjschoenfeld** [comment]
Thank you Pieter. This changes are all needed. Sorry I have been slow to respond. Please make a pull request against the develop branch when you feel it is ready.

**Comment by PGijsbers** [comment]
I think it's fine to merge it now :) new issues may emerge but I feel they are best tackled when they come by

**Comment by bjschoenfeld** [comment]
I reviewed the api in commit b7d2de1905c43022bfdece8bf169c02f8a9b4bbb
