### ISSUE TITLE
Streamline OpenML installation

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#27]
We use the openml package to compare our metafeatures with OpenML's. Since openml is directly installable with pip/pypi, we have to download it and then use `pip install .` in our environment. Is there anyway to streamline this install to avoid this extra step? Is there a convention for a separate requirements list for the test suite?

**Comment by bjschoenfeld** [comment]
I found an example in a setup.py that looks like this:
```
tests_require=[
        'docker[tls]==2.7',
],
```

**Comment by macetheace96** [comment]
Openml is now directly pip installable

**Comment by bjschoenfeld** [comment]
handled with #135
