### ISSUE TITLE
Refactor to make code more pythonic

### ISSUE THREAD

**Issue by PGijsbers** [byu-dml/metalearn#3]
Hi,

I was getting familiar with the code, and I noticed at times that some functions were very 'unpythonic', for instance keeping track of index counters (and manually incrementing them). I was wondering if this was purposely so (and if so, why).

I took the liberty of refactoring `common_operations` ([new](https://github.com/PGijsbers/metalearn/blob/development/metalearn/features/common_operations.py) & [old](https://github.com/PGijsbers/metalearn/blob/master/metalearn/features/common_operations.py)), as you can see it becomes a lot less verbose. I think it might be worthwhile to go through all of the code and refactor if possible. It may help make the code more maintainable and can lead to finding some bugs (i.e. the old `normalize` function did not work properly on integer arrays, as the floating point normalized column would be coerced to integer when being assigned to a column of the integer array). What do you think?

Regards

**Comment by bjschoenfeld** [comment]
Hi Pieter,

I looked over the new and old code and the changes you have made look good to me. Feel free to make things more pythonic, especially if it will remove bugs and improve performance.

Thanks!
