### ISSUE TITLE
Convert sample_rows/columns to int

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#35]
Metafeatures.compute has two boolean parameters to indicate whether to sample the rows/columns to reduce the computation time of metafeatures. Does it make more sense to use an integer, to specify the number of rows/columns to sample? None could indicate no sampling.

**Comment by bjschoenfeld** [comment]
@rlaboulaye What if we left the column and row sampling to the end-user? This puts onus on the user to decide which rows and columns to use. If they want metafeatures on the whole dataset, then they can pass the whole dataset.

We could go so far as to provide an auxiliary function which does the sampling for convenience.

**Comment by MichaelMMeskhi** [comment]
How would you look at offering a sampling technique. For example, the dataset is too large so instead some sampling technique can select important rows/columns to pass into Metafeatures.compute thus reducing size. This way they still get important metafeatures that represent that whole population. Correct me if I am wrong, this just makes some good sense in my head.

**Comment by bjschoenfeld** [comment]
@MichaelMMeskhi I am not sure I understand your point.

Currently we do offer a sampling option. We do not have a way to determine which rows/columns are important, so we sample uniformly at random. This reduces the compute time, as you know, while hopefully preserving metafeature values. Metafeatures are computed on sampled data only when the metafeatures are expensive to compute.

My questions are:
- should we keep the sampling option?
- If we sample, should the api be a number indicating how much to sample instead of a Boolean flag?
- If we do not sample, should we offer a staticmethod that will allow the user to sample their dataset easily?

One advantage to keeping the sampling is that the user does not have to determine which metafeatures are expensive to compute. The user does not have to make multiple calls to `compute` to get the cheap metafeatures on the whole dataset and expensive metafeatures on a sampled dataset.

**Comment by MichaelMMeskhi** [comment]
My bad, let me elaborate my point by answering your points:

- We should keep the sampling option but change the sampling strategy in a way to select most important rows/columns. 
- Yes and no. If the user is not sure about how to sample they can just pass `True` and let the API select the most suitable size of sample depending on population size. If they do know well let them pass an integer value of how many rows to sample.
- This could be an option for expert users (not offering sampling). I think we should keep sampling. I don't think it can hurt. 

All in all, I think sampling should stay but we should implement a better sampling strategy, one that can help sample most important rows and thus give a better representative sample of the population.

**Comment by bjschoenfeld** [comment]
I am leaning towards keeping sampling as well.

It is difficult to determine how many rows to sample. We chose a static 150k rows and 150 columns because it ran in about 5 minuts. How could we choose a smarter value? Should we use a percentage of the original size?

How do we determine which rows and columns are most important? For rows, we do keep a minimum number per class (default 2), but this only works for classification.

**Comment by MichaelMMeskhi** [comment]
Well let's say we have a population of size 1000, we need to decide the sample size. Let's choose a confidence interval of 99% to keep things strict and robust. And choose a margin of error of 4%. This will require us to sample almost 50%. Now the most important thing is to find a way of how to sample instead of size of sample. Size of sample can be easily tuned. You mentioned a sampling rule specific to classification, maybe we can have separate sampling rules for different problems? But then again that brings up problem [#37](https://github.com/byu-dml/metalearn/issues/37).

**Comment by bjschoenfeld** [comment]
Perhaps we should use a method like that to determine our sample size. With columns, it is difficult. Some datasets have 10k's of columns and our complexity on the columns for some metafeatures is at least O(n<sup>2</sup>) or maybe O(n<sup>3</sup>) in the number of columns. We are not sure yet.

**Comment by MichaelMMeskhi** [comment]
Regarding columns, wouldn't a simple feature selection method be able to identify a subset of columns that are most relevant thus decreasing the amount of columns to consider?

**Comment by bjschoenfeld** [comment]
That is a good idea. It would have to be fast enough to be worth while. Do you have any in mind?

**Comment by bjschoenfeld** [comment]
However, this does start to push towards the idea of dropping sampling altogether. There are many ways to select columns and perhaps that should be left to the user. Using a fancy algorithm complicates our code.

**Comment by MichaelMMeskhi** [comment]
What about offering all of these options to the user to choose from? They all have pros and cons. Speed vs. accuracy for example.

**Comment by bjschoenfeld** [comment]
More options means more development and maintenance work for us.

**Comment by MichaelMMeskhi** [comment]
Yes that is true. But yet we need some kind of solution sooner or later.

**Comment by bjschoenfeld** [comment]
We do have a working solution right now (whether it is good or not is another question), which is to sample a fixed amount uniformly at random from each class.

Perhaps this issue has gone a little out of scope. I will create another issue to determine how we sample, linking appropriate comments from this thread.

For now, given that we do sample uniformly at random from each class for the rows and simple uniform random for the columns, how should the sample size be chosen? Currently it is fixed at 150k by 150 and the user can only decide whether to sample.
