### ISSUE TITLE
Which metafeatures can be computed given a problem type?

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#37]
Once we allow for different problem types #13, we will need to determine which metafeatures can be computed for each problem type. I propose that in the metafeatures.json, we include this information as another field. It could look like: `"problem_types": ["Classification", "Regression"]`. This would allow us to get a list of all computable metafeatures, given the problem type. We can also validate the requested metafeatures against this list.

**Comment by MichaelMMeskhi** [comment]
This is a good idea. Meanwhile my research will help in determining what are some strong meta-features for each problem type and can be updated in the future. Again, all of this will surely help decrease computational costs and further improve results.

**Comment by bjschoenfeld** [comment]
This will become a natural issue once we support regression tasks. We can reopen then.
