### ISSUE TITLE
Metafeatures default random number seed chosen at random

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#38]
The current default random seed is 42. Does it make sense to use the same random seed if the user does not specify one? Would it make more sense to choose the seed at random, if one is not specified? The seed should be available to the user if they want to store which seed was used, in this case.

**Comment by MichaelMMeskhi** [comment]
Let's say the user is trying to run an experiment, then choosing a specific seed by the user makes sense or letting them know that the default seed is 42, for reproducibility. As for general run, I think randomly choosing a new seed will be best? To keep things "random".

**Comment by bjschoenfeld** [comment]
Those are my thoughts too. We want to keep runs "random" as much as possible, but still have the ability to reproduce results, if desired by the user.

I propose we set the default to `seed=None` and then randomly generate a seed in this case. The seed is stored in `self.seed` and the user can access that value after each run if s/he wants to store it for reproducibility. Of course, if the user passes a value for `seed`, then we use that.

**Comment by MichaelMMeskhi** [comment]
Yes, sounds like a perfect solution!
