### ISSUE TITLE
Smaller Test Datasets

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#39]
Tests with real datasets take 2-3 minutes to run. It would be nice during development to have tests that run much quicker. We could contrive datasets that still have all the features we want to test, but take much less time.

**Comment by MichaelMMeskhi** [comment]
Think of that "right" sampling method we can implement, we can use them as test datasets since they represent much larger datasets but contain most important metafeatures themselves.

**Comment by bjschoenfeld** [comment]
Yes, I was thinking we should greatly down-sample a real dataset. It should also have:

- missing values
- a column of completely missing values
- categorical values, including ints
- numerical values, including ints

It should take maybe 10 seconds to compute metafeatures - something fast but still noticeable.

**Comment by macetheace96** [comment]
would it be worth it to generate our own datasets for this problem or would it be better to just sample a real dataset?

**Comment by bjschoenfeld** [comment]
It does not matter to me whether we sample or generate our own. Sampling may be easier.

**Comment by bjschoenfeld** [comment]
We may still have to hand curate the dataset after sampling.

**Comment by MichaelMMeskhi** [comment]
Idea: Get a big dataset, fix it up to our needs. Then keep sampling it/generating small test sets.

**Comment by bjschoenfeld** [comment]
That could work. We just need to make sure we have identified all the qualities we want the test dataset(s) to have and then someone just needs to do it. We can always update the datasets if needed.

**Comment by MichaelMMeskhi** [comment]
There you go. Quite simple.

**Comment by bjschoenfeld** [comment]
We need a small dataset with known, hand computed metafeature values, so can test correctness. This should have been the first test we created.

**Comment by bjschoenfeld** [comment]
Handled with #79
