### ISSUE TITLE
Standardize metafeature architecture

### ISSUE THREAD

**Issue by csydvs** [byu-dml/metalearn#5]
We need to create a standard extensible way to handle metafeatures. We have proposed splitting them up as much as possible and then having them all follow from a standard interface, so that any reasonable subset can be called by the user.

**Comment by csydvs** [comment]
I have implemented a shared interface that all of these metafeatures will implement. I have not yet split up the metafeatures into more manageable groups than the three large ones that we have. However, it should now be much more straightforward to add additional metafeatures as a new class implementing Metafeature.

**Comment by bjschoenfeld** [comment]
This issue is obsolete. I think everything has been handled. If anything here needs to be addressed, let's open a new issue.
