### ISSUE TITLE
Desire for static list of relative compute times for metafeatures

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#50]
We have a request to list the relative computation time for our metafeatures. Users can then decide which ones they want to compute based on time. It could start as a relative list like, short, medium, long.

**Comment by macetheace96** [comment]
I don't know if this is still relevant, but I have a set of maybe 100 OpenML datasets that I computed metafeatures for a little while ago, including time, that we could use to determine this. If we don't have anything better I'll try to compare the times with that for now

**Comment by macetheace96** [comment]
Here's a list of the metafeatures with their mean compute times for over 100 datasets:

('NumberOfInstances_Time', 0.0012403747491669236)
('NumberOfFeatures_Time', 0.0012403747491669236)
('NumberOfClasses_Time', 0.0012403747491669236)
('NumberOfNumericFeatures_Time', 0.0012403747491669236)
('NumberOfCategoricalFeatures_Time', 0.0012403747491669236)
('RatioOfNumericFeatures_Time', 0.0012403747491669236)
('RatioOfCategoricalFeatures_Time', 0.0012403747491669236)
('Dimensionality_Time', 0.0025533430757578354)
('ClassEntropy_Time', 0.0054454594327692403)
('NumberOfMissingValues_Time', 0.0055479389882227134)
('RatioOfMissingValues_Time', 0.0055479389882227134)
('NumberOfInstancesWithMissingValues_Time', 0.0055479389882227134)
('RatioOfInstancesWithMissingValues_Time', 0.0055479389882227134)
('MeanClassProbability_Time', 0.0071131625370672571)
('StdevClassProbability_Time', 0.0071131625370672571)
('MinClassProbability_Time', 0.0071131625370672571)
('MaxClassProbability_Time', 0.0071131625370672571)
('MinorityClassSize_Time', 0.0071131625370672571)
('MajorityClassSize_Time', 0.0071131625370672571)
('MeanCategoricalAttributeEntropy_Time', 0.020497156165496647)
('MinCategoricalAttributeEntropy_Time', 0.020497156165496647)
('Quartile1CategoricalAttributeEntropy_Time', 0.020497156165496647)
('Quartile2CategoricalAttributeEntropy_Time', 0.020497156165496647)
('Quartile3CategoricalAttributeEntropy_Time', 0.020497156165496647)
('MaxCategoricalAttributeEntropy_Time', 0.020497156165496647)
('MeanCategoricalJointEntropy_Time', 0.031936200738650319)
('MinCategoricalJointEntropy_Time', 0.031936200738650319)
('Quartile1CategoricalJointEntropy_Time', 0.031936200738650319)
('Quartile2CategoricalJointEntropy_Time', 0.031936200738650319)
('Quartile3CategoricalJointEntropy_Time', 0.031936200738650319)
('MaxCategoricalJointEntropy_Time', 0.031936200738650319)
('MeanCategoricalMutualInformation_Time', 0.041038796218515139)
('MinCategoricalMutualInformation_Time', 0.041038796218515139)
('Quartile1CategoricalMutualInformation_Time', 0.041038796218515139)
('Quartile2CategoricalMutualInformation_Time', 0.041038796218515139)
('Quartile3CategoricalMutualInformation_Time', 0.041038796218515139)
('MaxCategoricalMutualInformation_Time', 0.041038796218515139)
('MeanCardinalityOfCategoricalFeatures_Time', 0.047585120675159479)
('StdevCardinalityOfCategoricalFeatures_Time', 0.047585120675159479)
('MinCardinalityOfCategoricalFeatures_Time', 0.047585120675159479)
('MaxCardinalityOfCategoricalFeatures_Time', 0.047585120675159479)
('MeanMeansOfNumericFeatures_Time', 0.092386502271507215)
('StdevMeansOfNumericFeatures_Time', 0.092386502271507215)
('MinMeansOfNumericFeatures_Time', 0.092386502271507215)
('MaxMeansOfNumericFeatures_Time', 0.092386502271507215)
('Quartile1MeansOfNumericFeatures_Time', 0.092386502271507215)
('Quartile2MeansOfNumericFeatures_Time', 0.092386502271507215)
('Quartile3MeansOfNumericFeatures_Time', 0.092386502271507215)
('MeanCardinalityOfNumericFeatures_Time', 0.093628248973199504)
('StdevCardinalityOfNumericFeatures_Time', 0.093628248973199504)
('MinCardinalityOfNumericFeatures_Time', 0.093628248973199504)
('MaxCardinalityOfNumericFeatures_Time', 0.093628248973199504)
('MeanSkewnessOfNumericFeatures_Time', 0.093698581059773758)
('StdevSkewnessOfNumericFeatures_Time', 0.093698581059773758)
('MinSkewnessOfNumericFeatures_Time', 0.093698581059773758)
('MaxSkewnessOfNumericFeatures_Time', 0.093698581059773758)
('Quartile1SkewnessOfNumericFeatures_Time', 0.093698581059773758)
('Quartile2SkewnessOfNumericFeatures_Time', 0.093698581059773758)
('Quartile3SkewnessOfNumericFeatures_Time', 0.093698581059773758)
('MeanKurtosisOfNumericFeatures_Time', 0.094142927760966347)
('StdevKurtosisOfNumericFeatures_Time', 0.094142927760966347)
('MinKurtosisOfNumericFeatures_Time', 0.094142927760966347)
('MaxKurtosisOfNumericFeatures_Time', 0.094142927760966347)
('Quartile1KurtosisOfNumericFeatures_Time', 0.094142927760966347)
('Quartile2KurtosisOfNumericFeatures_Time', 0.094142927760966347)
('Quartile3KurtosisOfNumericFeatures_Time', 0.094142927760966347)
('MeanStdDevOfNumericFeatures_Time', 0.094149266070092635)
('StdevStdDevOfNumericFeatures_Time', 0.094149266070092635)
('MinStdDevOfNumericFeatures_Time', 0.094149266070092635)
('MaxStdDevOfNumericFeatures_Time', 0.094149266070092635)
('Quartile1StdDevOfNumericFeatures_Time', 0.094149266070092635)
('Quartile2StdDevOfNumericFeatures_Time', 0.094149266070092635)
('Quartile3StdDevOfNumericFeatures_Time', 0.094149266070092635)
('EquivalentNumberOfCategoricalFeatures_Time', 0.096220107639537145)
('CategoricalNoiseToSignalRatio_Time', 0.13689774625441609)
('PredPCA1_Time', 0.14670105984336451)
('PredPCA2_Time', 0.14670105984336451)
('PredPCA3_Time', 0.14670105984336451)
('PredEigen1_Time', 0.14670105984336451)
('PredEigen2_Time', 0.14670105984336451)
('PredEigen3_Time', 0.14670105984336451)
('PredDet_Time', 0.14670105984336451)
('MeanNumericAttributeEntropy_Time', 0.18987696909765053)
('MinNumericAttributeEntropy_Time', 0.18987696909765053)
('Quartile1NumericAttributeEntropy_Time', 0.18987696909765053)
('Quartile2NumericAttributeEntropy_Time', 0.18987696909765053)
('Quartile3NumericAttributeEntropy_Time', 0.18987696909765053)
('MaxNumericAttributeEntropy_Time', 0.18987696909765053)
('RandomTreeDepth1ErrRate_Time', 0.32424219031082957)
('RandomTreeDepth1Kappa_Time', 0.32424219031082957)
('RandomTreeDepth2ErrRate_Time', 0.32626073681123074)
('RandomTreeDepth2Kappa_Time', 0.32626073681123074)
('RandomTreeDepth3ErrRate_Time', 0.32745670296295343)
('RandomTreeDepth3Kappa_Time', 0.32745670296295343)
('DecisionStumpErrRate_Time', 0.33495518896314835)
('DecisionStumpKappa_Time', 0.33495518896314835)
('NaiveBayesErrRate_Time', 0.63448864117003323)
('NaiveBayesKappa_Time', 0.63448864117003323)
('MeanNumericJointEntropy_Time', 0.7028934523376108)
('MinNumericJointEntropy_Time', 0.7028934523376108)
('Quartile1NumericJointEntropy_Time', 0.7028934523376108)
('Quartile2NumericJointEntropy_Time', 0.7028934523376108)
('Quartile3NumericJointEntropy_Time', 0.7028934523376108)
('MaxNumericJointEntropy_Time', 0.7028934523376108)
('LinearDiscriminantAnalysisErrRate_Time', 0.88477154224239596)
('LinearDiscriminantAnalysisKappa_Time', 0.88477154224239596)
('MeanNumericMutualInformation_Time', 1.687135038320084)
('MinNumericMutualInformation_Time', 1.687135038320084)
('Quartile1NumericMutualInformation_Time', 1.687135038320084)
('Quartile2NumericMutualInformation_Time', 1.687135038320084)
('Quartile3NumericMutualInformation_Time', 1.687135038320084)
('MaxNumericMutualInformation_Time', 1.687135038320084)
('EquivalentNumberOfNumericFeatures_Time', 1.8792629040680922)
('NumericNoiseToSignalRatio_Time', 2.0841665066681898)
('MeanCanonicalCorrelation_Time', 4.5575388997618917)
('StdevCanonicalCorrelation_Time', 4.5575388997618917)
('kNN1NErrRate_Time', 7.3702332917709796)
('kNN1NKappa_Time', 7.3702332917709796)

**Comment by bjschoenfeld** [comment]
That is a great list. Would it be too difficult to also get the standard deviation, min, and max?

**Comment by macetheace96** [comment]
yeah I actually already computed those at the same time, I'll put them up as well

**Comment by macetheace96** [comment]
Sorted by min:
'MeanCardinalityOfNumericFeatures_Time', 9.250640869140625e-05)
('StdevCardinalityOfNumericFeatures_Time', 9.250640869140625e-05)
('MinCardinalityOfNumericFeatures_Time', 9.250640869140625e-05)
('MaxCardinalityOfNumericFeatures_Time', 9.250640869140625e-05)
('MeanCanonicalCorrelation_Time', 0.00016927719116210938)
('StdevCanonicalCorrelation_Time', 0.00016927719116210938)
('MeanCardinalityOfCategoricalFeatures_Time', 0.00020122528076171875)
('StdevCardinalityOfCategoricalFeatures_Time', 0.00020122528076171875)
('MinCardinalityOfCategoricalFeatures_Time', 0.00020122528076171875)
('MaxCardinalityOfCategoricalFeatures_Time', 0.00020122528076171875)
('NumberOfInstances_Time', 0.00021672248840332031)
('NumberOfFeatures_Time', 0.00021672248840332031)
('NumberOfClasses_Time', 0.00021672248840332031)
('NumberOfNumericFeatures_Time', 0.00021672248840332031)
('NumberOfCategoricalFeatures_Time', 0.00021672248840332031)
('RatioOfNumericFeatures_Time', 0.00021672248840332031)
('RatioOfCategoricalFeatures_Time', 0.00021672248840332031)
('MeanMeansOfNumericFeatures_Time', 0.00026273727416992188)
('StdevMeansOfNumericFeatures_Time', 0.00026273727416992188)
('MinMeansOfNumericFeatures_Time', 0.00026273727416992188)
('MaxMeansOfNumericFeatures_Time', 0.00026273727416992188)
('Quartile1MeansOfNumericFeatures_Time', 0.00026273727416992188)
('Quartile2MeansOfNumericFeatures_Time', 0.00026273727416992188)
('Quartile3MeansOfNumericFeatures_Time', 0.00026273727416992188)
('MeanStdDevOfNumericFeatures_Time', 0.00027608871459960938)
('StdevStdDevOfNumericFeatures_Time', 0.00027608871459960938)
('MinStdDevOfNumericFeatures_Time', 0.00027608871459960938)
('MaxStdDevOfNumericFeatures_Time', 0.00027608871459960938)
('Quartile1StdDevOfNumericFeatures_Time', 0.00027608871459960938)
('Quartile2StdDevOfNumericFeatures_Time', 0.00027608871459960938)
('Quartile3StdDevOfNumericFeatures_Time', 0.00027608871459960938)
('MeanKurtosisOfNumericFeatures_Time', 0.0002765655517578125)
('StdevKurtosisOfNumericFeatures_Time', 0.0002765655517578125)
('MinKurtosisOfNumericFeatures_Time', 0.0002765655517578125)
('MaxKurtosisOfNumericFeatures_Time', 0.0002765655517578125)
('Quartile1KurtosisOfNumericFeatures_Time', 0.0002765655517578125)
('Quartile2KurtosisOfNumericFeatures_Time', 0.0002765655517578125)
('Quartile3KurtosisOfNumericFeatures_Time', 0.0002765655517578125)

('MeanCategoricalAttributeEntropy_Time', 0.0002803802490234375)
('MinCategoricalAttributeEntropy_Time', 0.0002803802490234375)
('Quartile1CategoricalAttributeEntropy_Time', 0.0002803802490234375)
('Quartile2CategoricalAttributeEntropy_Time', 0.0002803802490234375)
('Quartile3CategoricalAttributeEntropy_Time', 0.0002803802490234375)
('MaxCategoricalAttributeEntropy_Time', 0.0002803802490234375)
('MeanSkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('StdevSkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('MinSkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('MaxSkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('Quartile1SkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('Quartile2SkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('Quartile3SkewnessOfNumericFeatures_Time', 0.00028514862060546875)
('MeanCategoricalJointEntropy_Time', 0.00029253959655761719)
('MinCategoricalJointEntropy_Time', 0.00029253959655761719)
('Quartile1CategoricalJointEntropy_Time', 0.00029253959655761719)
('Quartile2CategoricalJointEntropy_Time', 0.00029253959655761719)
('Quartile3CategoricalJointEntropy_Time', 0.00029253959655761719)
('MaxCategoricalJointEntropy_Time', 0.00029253959655761719)
('MeanCategoricalMutualInformation_Time', 0.0002956390380859375)
('MinCategoricalMutualInformation_Time', 0.0002956390380859375)
('Quartile1CategoricalMutualInformation_Time', 0.0002956390380859375)
('Quartile2CategoricalMutualInformation_Time', 0.0002956390380859375)
('Quartile3CategoricalMutualInformation_Time', 0.0002956390380859375)
('MaxCategoricalMutualInformation_Time', 0.0002956390380859375)
('MeanNumericAttributeEntropy_Time', 0.00030255317687988281)
('MinNumericAttributeEntropy_Time', 0.00030255317687988281)
('Quartile1NumericAttributeEntropy_Time', 0.00030255317687988281)
('Quartile2NumericAttributeEntropy_Time', 0.00030255317687988281)
('Quartile3NumericAttributeEntropy_Time', 0.00030255317687988281)
('MaxNumericAttributeEntropy_Time', 0.00030255317687988281)
('MeanNumericMutualInformation_Time', 0.00031185150146484375)
('MinNumericMutualInformation_Time', 0.00031185150146484375)
('Quartile1NumericMutualInformation_Time', 0.00031185150146484375)
('Quartile2NumericMutualInformation_Time', 0.00031185150146484375)
('Quartile3NumericMutualInformation_Time', 0.00031185150146484375)
('MaxNumericMutualInformation_Time', 0.00031185150146484375)

('MeanNumericJointEntropy_Time', 0.00031256675720214844)
('MinNumericJointEntropy_Time', 0.00031256675720214844)
('Quartile1NumericJointEntropy_Time', 0.00031256675720214844)
('Quartile2NumericJointEntropy_Time', 0.00031256675720214844)
('Quartile3NumericJointEntropy_Time', 0.00031256675720214844)
('MaxNumericJointEntropy_Time', 0.00031256675720214844)
('Dimensionality_Time', 0.00046086311340332031)
('ClassEntropy_Time', 0.00083661079406738281)
('NumberOfMissingValues_Time', 0.00090527534484863281)
('RatioOfMissingValues_Time', 0.00090527534484863281)
('NumberOfInstancesWithMissingValues_Time', 0.00090527534484863281)
('RatioOfInstancesWithMissingValues_Time', 0.00090527534484863281)
('MeanClassProbability_Time', 0.0010242462158203125)
('StdevClassProbability_Time', 0.0010242462158203125)
('MinClassProbability_Time', 0.0010242462158203125)
('MaxClassProbability_Time', 0.0010242462158203125)
('MinorityClassSize_Time', 0.0010242462158203125)
('MajorityClassSize_Time', 0.0010242462158203125)
('PredPCA1_Time', 0.0030539035797119141)
('PredPCA2_Time', 0.0030539035797119141)
('PredPCA3_Time', 0.0030539035797119141)
('PredEigen1_Time', 0.0030539035797119141)
('PredEigen2_Time', 0.0030539035797119141)
('PredEigen3_Time', 0.0030539035797119141)
('PredDet_Time', 0.0030539035797119141)
('EquivalentNumberOfCategoricalFeatures_Time', 0.0042278766632080078)
('CategoricalNoiseToSignalRatio_Time', 0.0062305927276611328)
('EquivalentNumberOfNumericFeatures_Time', 0.0086472034454345703)
('NumericNoiseToSignalRatio_Time', 0.0144500732421875)
('RandomTreeDepth2ErrRate_Time', 0.1909489631652832)
('RandomTreeDepth2Kappa_Time', 0.1909489631652832)
('NaiveBayesErrRate_Time', 0.19121360778808594)
('NaiveBayesKappa_Time', 0.19121360778808594)
('kNN1NErrRate_Time', 0.19203305244445801)
('kNN1NKappa_Time', 0.19203305244445801)
('RandomTreeDepth3ErrRate_Time', 0.19225764274597168)
('RandomTreeDepth3Kappa_Time', 0.19225764274597168)
('RandomTreeDepth1ErrRate_Time', 0.19257450103759766)
('RandomTreeDepth1Kappa_Time', 0.19257450103759766)
('DecisionStumpErrRate_Time', 0.1926109790802002)
('DecisionStumpKappa_Time', 0.1926109790802002)
('LinearDiscriminantAnalysisErrRate_Time', 0.19605684280395508)
('LinearDiscriminantAnalysisKappa_Time', 0.19605684280395508)

**Comment by bjschoenfeld** [comment]
This is a great list. I am not sure how to make this a feature of this package, apart from something like #97. Create a new issue if a new idea comes up or is desired.
