### ISSUE TITLE
Metalearn assumes missing values are 'NaN', do we want this?

### ISSUE THREAD

**Issue by jaromrex** [byu-dml/metalearn#51]

**Comment by bjschoenfeld** [comment]
One alternative is to allow the user to specify the missing value token(s).

**Comment by MichaelMMeskhi** [comment]
Can allow the user to keep NaN or fill with mean or some other common technique.

**Comment by bjschoenfeld** [comment]
This is not a matter of imputing missing values, but identifying them. If a cell has `NaN` in it, we assume it is missing. Well, what about the empty string `''` or `None` or `'?'`? Should these be considered missing values? What about a custom token that a user/dataset might use, e.g. `'MISSING'`?

I see two solutions: 1) we treat `NaN` as the only missing value, or 2) we allow the user to input which values we should consider as missing values.

Solution 1 would imply that the user replace all their missing values with `NaN` before requesting metafeatures.

Solution 2 requires us to change our API.

**Comment by MichaelMMeskhi** [comment]
Solution 1 is the option then. You can give out a warning message reminding the user to check their dataset and replace missing values with NaN

**Comment by bjschoenfeld** [comment]
We shall not make any changes. We use `pandas.DataFrame.count` to determine the number of missing values.
