### ISSUE TITLE
Question/Discussion about Statistical Metafeatures implementations

### ISSUE THREAD

**Issue by PGijsbers** [byu-dml/metalearn#6]
Hi all,

I was looking at the code for statistical metafeatures and came across a few things I would like to discuss.

1. The statistical features are currently computed both on preprocessed data and raw data. Personally, I would leave the choice of preprocessing to the end-user. The end-user might not be interested in the effect of preprocessing, or might value other preprocessing techniques (eg. normalization instead of minmax scaling, no one-hot encoding). In effect, this would mean the module would compute the features on the data as is. If the user would like information on the preprocessed data, he will also invoke the module on that, too.

2. Skewness and Kurtosis are computed per-class per-column and their absolute values are averaged. I do not think either is one of the suggested metafeatures? From what I understand, normally skewness and kurtosis are only computed by column (and aggregate statistics over those values are then computed). Is there any particular reason for this implementation?

Kind regards

**Comment by cgcbyu** [comment]
1. Yes, we should compute on whatever data is presented to the metafeature extractor. Raw is one type, but I can also see a user wanting to run the metafeature extractor later on in the pipeline after the data may have been modified by primitives. So the data should be an input to the metafeature extractor.
2. I believe the implementation comes from Reif et al (in R, and we ported it to Python), so not sure why it is as it is. If it is incorrect/not very good, please feel free to change the code accordingly.

**Comment by rlaboulaye** [comment]
As Christophe indicated, the current metafeatures were ported from an R script made available alongside a survey of current metafeatures by Reif et al. As such the decision to include kurtosis and skewness for preprocessed data as well as the decision to calculate skewness by class in addition to column were made by the authors of that paper. It would be good for us to revisit the paper to see the authors' justification for their methodology. Christophe, do you remember the title of the paper?

**Comment by cgcbyu** [comment]
@article{reifetal14,
	author = "Reif, M. and Shafait, F. and Goldstein, M. and Breuel, T. and Dengel, A.",
	title = "Automatic Classifier Selection for Non-experts",
	journal = "Pattern Analysis \& Applications",
	volume = "17",
	number = "1",
	pages = "83-96",
	year = 2014}

**Comment by rlaboulaye** [comment]
Thank you.

**Comment by PGijsbers** [comment]
I tried to look for the actual code behind the paper, but couldn't find it. It mentions that it's open source so I figure it _should_ be easy to find, but for some reason I seem to miss it 😅 do you have a link?

**Comment by cgcbyu** [comment]
Attached. I believe this is it.
[meta-features-1.0.r.zip](https://github.com/byu-dml/metalearn/files/1555877/meta-features-1.0.r.zip)

**Comment by bjschoenfeld** [comment]
The statistical meta-features are no longer computed per class. We eliminated as much preprocessing as possible, but some is unavoidable. See #12. Feel free to open new issues on this general subject as needed.
