### ISSUE TITLE
Verbose Flag

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#62]
Because computing metafeatures on some datasets can take a long time, it would be nice to have some output indicating how much progress has been made so far. Having a `verbose` parameter in the `compute` function seems reasonable. Default is `False`, it could print which metafeatures it is currently working on.

**Comment by macetheace96** [comment]
What kind of format should the output be in?

**Comment by bjschoenfeld** [comment]
I was thinking we could just print the metafeature name. Is this feature desired? Is there another way that would be more useful?

**Comment by bjschoenfeld** [comment]
What about a callback function? This would give the user flexibility to do whatever they want. It could accept as parameters the current metafeature being computed and the values of the already computed metafeatures. Thoughts?

**Comment by bjschoenfeld** [comment]
We will just print the metafeature name being computed. If anyone wants something more, open an issue and we will consider it. Handled with 44f04a2c52df3065216542af2c90d1d26424ff4d
