### ISSUE TITLE
what should be returned for the the third component of PCA for datasets with only 2 columns?

### ISSUE THREAD

**Issue by jaromrex** [byu-dml/metalearn#68]
right now, metalearn always returns info on three components after doing PCA.  If a dataset has only two columns, the third component values are returned as "Nan".  would it be more helpful if these were returned as "0"?

**Comment by jaromrex** [comment]
It is now changed to return "0" for this case.  Does anybody have any better suggestion or think this is a bad idea?

**Comment by bjschoenfeld** [comment]
#70 decided to return 0 for extra pca components
