### ISSUE TITLE
Need column types for test datasets

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#74]
We do not have the true column types for test datasets. For each test dataset, we need to go to their source, get the column types for each dataset, and add that information alongside the data.

**Comment by bjschoenfeld** [comment]
The new small test dataset is in an arff file, which has column types.

**Comment by macetheace96** [comment]
The problem with adding column types to the datasets is that most of the are CSV format, and as far as I know there's no way to specify data types in a CSV file. Instead I've added the column types to the `test_dataset_metadata.json` file. If that's not acceptable then I also have the datasets downloaded from OpenML in arff format and we can parse those instead.

**Comment by macetheace96** [comment]
Should we do this for just the test datasets that we use (sick_train and small_test) or for all of the ones we have?

**Comment by bjschoenfeld** [comment]
Just the test datasets is fine

**Comment by bjschoenfeld** [comment]
handled in 992c1a44415848f8e1c7413e2e17c2c920bf5c48
