### ISSUE TITLE
How do we want to identify target-dependent metafeatures?

### ISSUE THREAD

**Issue by jaromrex** [byu-dml/metalearn#78]
Currently they are identified by parsing the json file recursively for any parameters that are target dependent.  This only becomes an issue if there is a function which takes "Y" as a parameter but also returns parameters that are not dependent on "Y".  Currently, the _get_sample_of_rows function is the only offender, and this is accounted for explicitly in the _is_target_dependent function, but we don't know what future function might also have this behavior.

Another possible way of identifying them, which would solve this issue, is if the json file had a field for metafeatures that labels them as target dependent

**Comment by bjschoenfeld** [comment]
handled with #87
