### ISSUE TITLE
int64 not JSON serializable

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#84]
This code is being used in a couple places now to handle this issue:

for key, value in computed_mfs.items():
           if 'int' in str(type(value)):
                       computed_mfs[key] = int(value)
           elif 'float' in str(type(value)):
                       computed_mfs[key] = float(value)
           else:
                        raise Exception('unhandled type: {}'.format(type(value)))

**Comment by macetheace96** [comment]
So there are two solutions I can see to this problem, either we can port that same code from above into `metafeatures.py` and cast everything to the proper type just before returning, or we can go through each method that uses numpy and set the default dtype to `int` or `float`
