### ISSUE TITLE
Return metafeatures as JSON serializable object

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#98]
The current output structure of the compute function is a `pandas.DataFrame` with one row and each column is the metafeature name. This is a bit awkward. At the very least, it should have been a `pandas.Series` with metafeature names as the index.

A dictionary is another simple alternative. Moving forward, especially with items like #93, a dictionary/JSON-like structure will be much more usable for users. This will give us greater flexibility as well to return more and cleaner information. (For example, having the `_Time` metafeatures could be changed to use a dictionary which maps metafeature name to another dictionary which has keys `value` and `time`, or something similar.)

The first step is defining a schema for the result object. This gives users a document to know how to parse the output and helps us validate our output. Schemas are flexible for when we need to make changes to our output.

Note #84.

**Comment by macetheace96** [comment]
I think returning a dictionary is a great idea, it would even help solve our timeout workaround with the `multiprocessing().Queue()` as we could simply use a `multiprocessing.Dict()` instead
